import { SubsidyScheme } from "./types";

// 靜態資料：當未設定 Supabase 時，App 仍可運作。
// 內容同 supabase/seed.sql 一致，方便 demo 同 admin 更新。
// 官方連結為佔位符（placeholder），可由 admin 後台更新。

const COMMON_DISCLAIMER =
  "本系統只幫你整理資料及估計，不代表政府已批准申請。最終批核以政府部門公佈為準。請以官方連結最新資料為準。";

export const SCHEMES: SubsidyScheme[] = [
  {
    id: "11111111-1111-1111-1111-111111111111",
    slug: "school-textbook-assistance",
    nameZh: "學校書簿津貼計劃",
    nameEn: "School Textbook Assistance Scheme",
    category: "上學開支",
    audience: ["student", "low_income"],
    summary:
      "幫低收入家庭俾返書簿同部分學習雜費。合資格學生可以攞全額或半額津貼。",
    suitableFor: "就讀小學或中學、家庭收入較低嘅學生。",
    notSuitableFor:
      "正領取綜援嘅家庭（綜援已包學校相關津貼，唔需要重複申請）。",
    eligibility: [
      "學生就讀本地小學或中學日校",
      "通過學生資助處嘅家庭入息審查",
      "並非正領取綜援",
    ],
    documents: [
      "applicant_id",
      "student_id",
      "student_proof",
      "address_proof",
      "income_proof",
      "bank_account",
    ],
    steps: [
      { order: 1, text: "第一步：先睇你屋企有冇讀緊小學或中學嘅學生。" },
      {
        order: 2,
        text: "第二步：準備身份證、學生證明、住址證明、收入證明。",
      },
      { order: 3, text: "第三步：填學生資助處「學生資助計劃」綜合申請表。" },
      { order: 4, text: "第四步：連同文件副本郵寄或網上交俾學生資助處。" },
      { order: 5, text: "第五步：等政府審查，再睇通知書知結果同金額。" },
    ],
    officialUrl: "https://www.wfsfaa.gov.hk/sfo/tc/index.htm",
    formUrl: "https://www.wfsfaa.gov.hk/sfo/tc/primarysecondary/tt/forms.php",
    department: "在學資助處（學生資助處）",
    phone: "2802 2345",
    lastVerified: "2026-06-01",
    disclaimer: COMMON_DISCLAIMER,
    rule: {
      gradeLevels: ["primary", "secondary"],
      maxIncomeBand: "20k_30k",
      excludeIfCssa: true,
      boostSingleParent: true,
      boostNewArrival: true,
    },
    active: true,
  },
  {
    id: "22222222-2222-2222-2222-222222222222",
    slug: "student-travel-subsidy",
    nameZh: "學生車船津貼計劃",
    nameEn: "Student Travel Subsidy Scheme",
    category: "交通開支",
    audience: ["student", "low_income"],
    summary: "幫住得遠、要搭車返學嘅低收入學生，補貼部分車船交通費。",
    suitableFor: "需要搭車船返學、屋企收入較低嘅學生。",
    notSuitableFor: "住喺學校附近、唔使付車費，或可步行返學嘅學生。",
    eligibility: [
      "學生就讀本地日校（小學至大專）",
      "居住地距離學校較遠、需要付公共交通費",
      "通過家庭入息審查",
    ],
    documents: [
      "applicant_id",
      "student_id",
      "student_proof",
      "address_proof",
      "income_proof",
      "bank_account",
    ],
    steps: [
      { order: 1, text: "第一步：睇下個學生係咪要搭車船先返到學校。" },
      { order: 2, text: "第二步：準備身份證、學生證明、住址證明、收入證明。" },
      { order: 3, text: "第三步：填學生資助處「學生資助計劃」申請表。" },
      { order: 4, text: "第四步：交俾學生資助處。" },
      { order: 5, text: "第五步：等通知，批咗就會過數入你銀行戶口。" },
    ],
    officialUrl: "https://www.wfsfaa.gov.hk/sfo/tc/index.htm",
    formUrl: "https://www.wfsfaa.gov.hk/sfo/tc/primarysecondary/sts/intro.htm",
    department: "在學資助處（學生資助處）",
    phone: "2802 2345",
    lastVerified: "2026-06-01",
    disclaimer: COMMON_DISCLAIMER,
    rule: {
      gradeLevels: ["primary", "secondary", "tertiary"],
      maxIncomeBand: "20k_30k",
      travelRelated: true,
      boostSingleParent: true,
      boostNewArrival: true,
    },
    active: true,
  },
  {
    id: "33333333-3333-3333-3333-333333333333",
    slug: "internet-access-subsidy",
    nameZh: "上網費津貼計劃",
    nameEn: "Subsidy Scheme for Internet Access Charges",
    category: "上學開支",
    audience: ["student", "low_income"],
    summary: "幫有學生嘅低收入家庭，補貼部分屋企上網費，方便網上學習。",
    suitableFor: "屋企有學生、需要上網做功課或網上學習嘅低收入家庭。",
    notSuitableFor: "家庭收入較高、或者已無在學子女嘅家庭。",
    eligibility: [
      "家庭有就讀中小學或以下嘅學生",
      "正領取綜援，或通過家庭入息審查",
      "每戶一年一次定額津貼",
    ],
    documents: [
      "applicant_id",
      "student_id",
      "student_proof",
      "address_proof",
      "income_proof",
      "bank_account",
    ],
    steps: [
      { order: 1, text: "第一步：睇下屋企有冇學生要上網學習。" },
      { order: 2, text: "第二步：準備身份證、學生證明、住址證明、收入或綜援證明。" },
      { order: 3, text: "第三步：填上網費津貼申請表。" },
      { order: 4, text: "第四步：交俾學生資助處或指定機構。" },
      { order: 5, text: "第五步：等通知，批咗會發放定額津貼。" },
    ],
    officialUrl: "https://www.wfsfaa.gov.hk/sfo/tc/index.htm",
    formUrl: "https://www.wfsfaa.gov.hk/sfo/tc/primarysecondary/itssa/intro.htm",
    department: "在學資助處（學生資助處）",
    phone: "2802 2345",
    lastVerified: "2026-06-01",
    disclaimer: COMMON_DISCLAIMER,
    rule: {
      gradeLevels: ["kindergarten", "primary", "secondary"],
      maxIncomeBand: "20k_30k",
      internetRelated: true,
      boostNewArrival: true,
    },
    active: true,
  },
  {
    id: "44444444-4444-4444-4444-444444444444",
    slug: "kindergarten-fee-remission",
    nameZh: "幼稚園及幼兒中心學費減免計劃",
    nameEn: "Kindergarten and Child Care Centre Fee Remission Scheme",
    category: "上學開支",
    audience: ["student", "low_income"],
    summary: "幫有幼稚園或幼兒中心小朋友嘅低收入家庭，減免部分學費。",
    suitableFor: "有就讀幼稚園或幼兒中心子女、收入較低嘅家庭。",
    notSuitableFor: "子女已升上小學或以上、或者收入超出上限嘅家庭。",
    eligibility: [
      "子女就讀參加計劃嘅幼稚園或幼兒中心",
      "通過家庭入息審查",
      "可申請全免或半免學費",
    ],
    documents: [
      "applicant_id",
      "student_id",
      "student_proof",
      "address_proof",
      "income_proof",
      "bank_account",
    ],
    steps: [
      { order: 1, text: "第一步：睇下你個小朋友係咪讀緊幼稚園或幼兒中心。" },
      { order: 2, text: "第二步：準備身份證、出世紙、住址證明、收入證明。" },
      { order: 3, text: "第三步：填學費減免申請表。" },
      { order: 4, text: "第四步：交俾學生資助處。" },
      { order: 5, text: "第五步：等通知，批咗會直接減學費。" },
    ],
    officialUrl: "https://www.wfsfaa.gov.hk/sfo/tc/index.htm",
    formUrl:
      "https://www.wfsfaa.gov.hk/sfo/tc/preprimary/kcfrs/intro.htm",
    department: "在學資助處（學生資助處）",
    phone: "2802 2345",
    lastVerified: "2026-06-01",
    disclaimer: COMMON_DISCLAIMER,
    rule: {
      gradeLevels: ["kindergarten"],
      maxIncomeBand: "30k_40k",
      boostSingleParent: true,
      boostNewArrival: true,
    },
    active: true,
  },
  {
    id: "55555555-5555-5555-5555-555555555555",
    slug: "cssa-student-support",
    nameZh: "綜援學生相關支援",
    nameEn: "Comprehensive Social Security Assistance (Student-related)",
    category: "綜合援助",
    audience: ["low_income", "student"],
    summary:
      "已領取綜援嘅家庭，子女讀書嘅學習津貼通常已經包喺綜援度，毋須另外申請書簿等津貼。",
    suitableFor: "正領取綜援、有在學子女嘅家庭。",
    notSuitableFor: "未領取綜援嘅家庭（應改為申請學生資助計劃）。",
    eligibility: [
      "家庭正領取綜援",
      "有就讀幼稚園至大專嘅在學子女",
      "學習開支津貼隨綜援個案發放",
    ],
    documents: [
      "applicant_id",
      "student_id",
      "student_proof",
      "cssa_proof",
      "bank_account",
    ],
    steps: [
      { order: 1, text: "第一步：確認你屋企正領緊綜援。" },
      { order: 2, text: "第二步：準備綜援文件、學生證明、身份證。" },
      { order: 3, text: "第三步：向你個案嘅社會保障部職員講有在學子女。" },
      { order: 4, text: "第四步：交學生相關證明俾社會福利署。" },
      { order: 5, text: "第五步：學習津貼會隨綜援一齊發放。" },
    ],
    officialUrl: "https://www.swd.gov.hk/tc/index/site_pubsvc/page_socsecu/",
    formUrl: "https://www.swd.gov.hk/tc/index/site_pubsvc/page_socsecu/sub_comprehens/",
    department: "社會福利署",
    phone: "2343 2255",
    lastVerified: "2026-06-01",
    disclaimer: COMMON_DISCLAIMER,
    rule: {
      requiresCssa: true,
      boostSen: true,
      boostSingleParent: true,
    },
    active: true,
  },
  {
    id: "66666666-6666-6666-6666-666666666666",
    slug: "working-family-allowance",
    nameZh: "在職家庭津貼計劃",
    nameEn: "Working Family Allowance Scheme",
    category: "綜合援助",
    audience: ["low_income"],
    summary:
      "幫有人返工但收入唔高嘅家庭。除咗家庭津貼，仲有兒童津貼幫補在學子女開支。",
    suitableFor: "有家庭成員返工、收入唔高、又有在學子女嘅家庭。",
    notSuitableFor: "正領取綜援嘅家庭（綜援同在職家庭津貼唔可以同時領取）。",
    eligibility: [
      "家庭有成員達到每月工時要求",
      "家庭收入及資產低於上限",
      "並非領取綜援",
    ],
    documents: [
      "applicant_id",
      "student_id",
      "student_proof",
      "address_proof",
      "income_proof",
      "bank_account",
      "tenancy_agreement",
    ],
    steps: [
      { order: 1, text: "第一步：睇下屋企有冇人返緊工，又有冇在學子女。" },
      { order: 2, text: "第二步：準備身份證、入息證明、工時證明、住址證明。" },
      { order: 3, text: "第三步：填在職家庭津貼申請表。" },
      { order: 4, text: "第四步：交俾在職家庭津貼辦事處。" },
      { order: 5, text: "第五步：等通知，批咗會按月或一筆過過數。" },
    ],
    officialUrl: "https://www.wfsfaa.gov.hk/wfao/tc/index.htm",
    formUrl: "https://www.wfsfaa.gov.hk/wfao/tc/application/forms.htm",
    department: "在職家庭津貼辦事處",
    phone: "2558 3000",
    lastVerified: "2026-06-01",
    disclaimer: COMMON_DISCLAIMER,
    rule: {
      maxIncomeBand: "30k_40k",
      excludeIfCssa: true,
      boostSingleParent: true,
      boostNewArrival: true,
    },
    active: true,
  },

  // ===== 長者 / 殘疾 群組（金額、年齡、資產上限每年由政府公布，需人手核實）=====

  // 7. 長者生活津貼 OALA
  {
    id: "77777777-7777-7777-7777-777777777777",
    slug: "old-age-living-allowance",
    nameZh: "長者生活津貼",
    nameEn: "Old Age Living Allowance (OALA)",
    category: "長者津貼",
    audience: ["elderly", "low_income"],
    summary:
      "俾 65 歲或以上、收入同資產唔多嘅長者嘅每月現金津貼。金額同資產上限每年由政府公布，請以官方為準。",
    suitableFor: "65 歲或以上、收入及資產較少嘅長者。",
    notSuitableFor: "資產或收入超出上限、或正領取綜援嘅長者（唔可以同時領取）。",
    eligibility: [
      "年滿 65 歲",
      "為香港居民並符合居港規定",
      "每月入息及資產不超過政府訂定上限（每年公布）",
      "並非同時領取綜援或高齡津貼",
    ],
    documents: ["applicant_id", "age_proof", "address_proof", "income_proof", "asset_proof", "bank_account"],
    steps: [
      { order: 1, text: "第一步：睇下你係咪夠 65 歲。" },
      { order: 2, text: "第二步：準備身份證、住址證明、收入同銀行結單。" },
      { order: 3, text: "第三步：填長者生活津貼申請表。" },
      { order: 4, text: "第四步：交俾社會福利署。" },
      { order: 5, text: "第五步：批咗會每月過錢入你戶口。" },
    ],
    officialUrl: "https://www.swd.gov.hk/tc/index/site_pubsvc/page_socsecu/sub_ssallowance/",
    formUrl: "https://www.swd.gov.hk/tc/index/site_pubsvc/page_socsecu/sub_ssallowance/",
    department: "社會福利署（社會保障）",
    phone: "2343 2255",
    lastVerified: "2026-06-01",
    disclaimer: COMMON_DISCLAIMER,
    rule: {
      requiresElderly: true,
      minAgeBand: "65_69",
      maxAssetBand: "medium",
      maxIncomeBand: "10k_20k",
      excludeIfCssa: true,
      meansTested: true,
      boostLivingAlone: true,
    },
    active: true,
  },

  // 8. 高齡津貼（生果金）OAA
  {
    id: "88888888-8888-8888-8888-888888888888",
    slug: "old-age-allowance",
    nameZh: "高齡津貼（生果金）",
    nameEn: "Old Age Allowance (OAA)",
    category: "長者津貼",
    audience: ["elderly"],
    summary:
      "俾 70 歲或以上長者嘅每月現金津貼，唔使入息審查。金額每年由政府公布。",
    suitableFor: "70 歲或以上嘅香港長者。",
    notSuitableFor: "未夠 70 歲，或已領取長者生活津貼 / 綜援嘅長者。",
    eligibility: [
      "年滿 70 歲",
      "為香港居民並符合居港規定",
      "毋須入息或資產審查",
      "不可同時領取長者生活津貼或綜援",
    ],
    documents: ["applicant_id", "age_proof", "address_proof", "bank_account"],
    steps: [
      { order: 1, text: "第一步：睇下你係咪夠 70 歲。" },
      { order: 2, text: "第二步：準備身份證同銀行戶口資料。" },
      { order: 3, text: "第三步：填高齡津貼申請表。" },
      { order: 4, text: "第四步：交俾社會福利署。" },
      { order: 5, text: "第五步：批咗會每月過錢入你戶口。" },
    ],
    officialUrl: "https://www.swd.gov.hk/tc/index/site_pubsvc/page_socsecu/sub_ssallowance/",
    formUrl: "https://www.swd.gov.hk/tc/index/site_pubsvc/page_socsecu/sub_ssallowance/",
    department: "社會福利署（社會保障）",
    phone: "2343 2255",
    lastVerified: "2026-06-01",
    disclaimer: COMMON_DISCLAIMER,
    rule: {
      requiresElderly: true,
      minAgeBand: "70_plus",
      excludeIfCssa: true,
      meansTested: false,
    },
    active: true,
  },

  // 9. 長者醫療券
  {
    id: "99999999-9999-9999-9999-999999999999",
    slug: "elderly-health-care-voucher",
    nameZh: "長者醫療券",
    nameEn: "Elderly Health Care Voucher Scheme",
    category: "醫療支援",
    audience: ["elderly"],
    summary:
      "俾 65 歲或以上長者用嚟睇私家醫生、牙醫、中醫等基層醫療服務嘅醫療券。每年金額由政府公布。",
    suitableFor: "65 歲或以上、想睇私家基層醫療嘅長者。",
    notSuitableFor: "未夠 65 歲嘅人士。",
    eligibility: [
      "年滿 65 歲",
      "持有效香港身份證",
      "醫療券可用於已登記嘅醫療服務提供者",
    ],
    documents: ["applicant_id", "age_proof"],
    steps: [
      { order: 1, text: "第一步：睇下你係咪夠 65 歲。" },
      { order: 2, text: "第二步：帶身份證去睇已登記嘅醫生或牙醫。" },
      { order: 3, text: "第三步：睇醫生時話用醫療券找數。" },
      { order: 4, text: "第四步：系統會自動喺你戶口扣醫療券。" },
      { order: 5, text: "第五步：唔使另外攞現金，直接抵扣診金。" },
    ],
    officialUrl: "https://www.hcv.gov.hk/tc/pub/index.html",
    formUrl: "https://www.hcv.gov.hk/tc/pub/index.html",
    department: "衞生署（醫療券計劃）",
    phone: "2838 2311",
    lastVerified: "2026-06-01",
    disclaimer: COMMON_DISCLAIMER,
    rule: {
      requiresElderly: true,
      minAgeBand: "65_69",
      medicalRelated: true,
      meansTested: false,
    },
    active: true,
  },

  // 10. 傷殘津貼
  {
    id: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    slug: "disability-allowance",
    nameZh: "傷殘津貼",
    nameEn: "Disability Allowance",
    category: "殘疾支援",
    audience: ["disability"],
    summary:
      "俾經評估為嚴重殘疾嘅香港居民嘅每月現金津貼，唔使入息審查。分普通同高額兩種。",
    suitableFor: "經醫生評估為嚴重殘疾嘅人士（任何年齡）。",
    notSuitableFor: "未經評估、或殘疾程度未達標準嘅人士。",
    eligibility: [
      "經衞生署 / 醫院管理局醫生證明為嚴重殘疾",
      "為香港居民並符合居港規定",
      "毋須入息或資產審查",
      "高額津貼須經常需要他人照顧",
    ],
    documents: ["applicant_id", "address_proof", "disability_proof", "bank_account"],
    steps: [
      { order: 1, text: "第一步：搵醫生做殘疾評估。" },
      { order: 2, text: "第二步：準備身份證、住址證明同醫生證明。" },
      { order: 3, text: "第三步：填傷殘津貼申請表。" },
      { order: 4, text: "第四步：交俾社會福利署。" },
      { order: 5, text: "第五步：批咗會每月過錢入你戶口。" },
    ],
    officialUrl: "https://www.swd.gov.hk/tc/index/site_pubsvc/page_socsecu/sub_ssallowance/",
    formUrl: "https://www.swd.gov.hk/tc/index/site_pubsvc/page_socsecu/sub_ssallowance/",
    department: "社會福利署（社會保障）",
    phone: "2343 2255",
    lastVerified: "2026-06-01",
    disclaimer: COMMON_DISCLAIMER,
    rule: {
      requiresDisability: true,
      meansTested: false,
      boostLivingAlone: true,
    },
    active: true,
  },

  // 11. 公共交通費用補貼 / $2 乘車優惠
  {
    id: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
    slug: "public-transport-subsidy",
    nameZh: "公共交通費用補貼 / $2 乘車優惠",
    nameEn: "Public Transport Fare Subsidy / $2 Concessionary Fares",
    category: "交通開支",
    audience: ["elderly", "disability", "low_income"],
    summary:
      "$2 乘車優惠俾長者及合資格殘疾人士用優惠票價搭車船；公共交通費用補貼則幫返交通開支較高嘅市民。詳情及年齡以官方為準。",
    suitableFor: "長者、合資格殘疾人士，或每月交通開支較高嘅市民。",
    notSuitableFor: "不符合年齡 / 殘疾資格，而交通開支又唔高嘅人士。",
    eligibility: [
      "$2 優惠：合資格長者及殘疾人士，用個人八達通或樂悠咭",
      "公共交通費用補貼：每月合資格交通開支超過指定水平",
      "確實年齡及金額以政府公布為準",
    ],
    documents: ["applicant_id", "age_proof"],
    steps: [
      { order: 1, text: "第一步：睇下你係咪長者或合資格殘疾人士。" },
      { order: 2, text: "第二步：申請 / 使用個人八達通或樂悠咭。" },
      { order: 3, text: "第三步：搭車船時嘟卡，自動用優惠票價。" },
      { order: 4, text: "第四步：交通費補貼會按你嘅實際車費計算。" },
      { order: 5, text: "第五步：補貼會經指定途徑發放（詳情睇官方）。" },
    ],
    officialUrl: "https://www.gov.hk/tc/residents/transport/transportfare/",
    formUrl: "https://www.gov.hk/tc/residents/transport/transportfare/",
    department: "勞工及福利局 / 運輸署",
    phone: "187 2333",
    lastVerified: "2026-06-01",
    disclaimer: COMMON_DISCLAIMER,
    rule: {
      travelRelated: true,
      meansTested: false,
      boostLivingAlone: true,
    },
    active: true,
  },
];

export function getSchemeById(id: string): SubsidyScheme | undefined {
  return SCHEMES.find((s) => s.id === id || s.slug === id);
}
