-- =============================================================
-- 初始種子資料 (seed)
-- 6 個常見學生津貼。官方連結為佔位符，可由 admin 後台更新。
-- 喺 schema.sql + rls.sql 之後執行。
-- =============================================================

insert into public.subsidy_schemes
  (id, slug, name_zh, name_en, category, summary, suitable_for, not_suitable_for,
   eligibility, documents, steps, official_url, form_url, department, phone,
   last_verified, disclaimer, rule, active)
values
-- 1. 學校書簿津貼
('11111111-1111-1111-1111-111111111111',
 'school-textbook-assistance',
 '學校書簿津貼計劃',
 'School Textbook Assistance Scheme',
 '上學開支',
 '幫低收入家庭俾返書簿同部分學習雜費。合資格學生可以攞全額或半額津貼。',
 '就讀小學或中學、家庭收入較低嘅學生。',
 '正領取綜援嘅家庭（綜援已包學校相關津貼，唔需要重複申請）。',
 '["學生就讀本地小學或中學全日制日校", "申請人為學生嘅家長或監護人", "學生為未婚香港居民，並在港有居留權／入境權，或不受逗留條件限制嘅居留許可", "家庭須通過學生資助處入息審查（按「經調整家庭收入」計算，分全額或半額）", "並非正領取綜援（綜援家庭嘅書簿等開支由社署直接支付，毋須重複申請）", "持訪客簽證、雙程證、學生簽證或其受養人不合資格"]'::jsonb,
 '["applicant_id","student_id","student_proof","address_proof","income_proof","bank_account"]'::jsonb,
 '[{"order":1,"text":"第一步：先睇你屋企有冇讀緊小學或中學嘅學生。"},{"order":2,"text":"第二步：準備身份證、學生證明、住址證明、收入證明。"},{"order":3,"text":"第三步：填學生資助處「學生資助計劃」綜合申請表。"},{"order":4,"text":"第四步：連同文件副本郵寄或網上交俾學生資助處。"},{"order":5,"text":"第五步：等政府審查，再睇通知書知結果同金額。"}]'::jsonb,
 'https://www.wfsfaa.gov.hk/tc/sfo/primarysecondary/tt/overview.php',
 'https://www.wfsfaa.gov.hk/tc/sfo/primarysecondary/tt/procedures.php',
 '在學資助處（學生資助處）',
 '2802 2345',
 '2026-06-01',
 '本系統只幫你整理資料及估計，不代表政府已批准申請。最終批核以政府部門公佈為準。請以官方連結最新資料為準。',
 '{"gradeLevels":["primary","secondary"],"maxIncomeBand":"20k_30k","excludeIfCssa":true,"boostSingleParent":true,"boostNewArrival":true}'::jsonb,
 true),

-- 2. 學生車船津貼
('22222222-2222-2222-2222-222222222222',
 'student-travel-subsidy',
 '學生車船津貼計劃',
 'Student Travel Subsidy Scheme',
 '交通開支',
 '幫住得遠、要搭車返學嘅低收入學生，補貼部分車船交通費。',
 '需要搭車船返學、屋企收入較低嘅學生。',
 '住喺學校附近、唔使付車費，或可步行返學嘅學生。',
 '["學生就讀屬車船津貼類別嘅學校（中小學，或認可院校全日制第一學位以下課程）", "申請人為學生嘅家長或監護人；學生為未婚香港居民並具香港居留身份（須附證明）", "住所距離學校超過 10 分鐘步行路程，並須以公共交通工具返學", "家庭須通過學生資助處入息審查", "並非正領取綜援（綜援家庭嘅交通費由社署支付）；夜校學生不適用"]'::jsonb,
 '["applicant_id","student_id","student_proof","address_proof","income_proof","bank_account"]'::jsonb,
 '[{"order":1,"text":"第一步：睇下個學生係咪要搭車船先返到學校。"},{"order":2,"text":"第二步：準備身份證、學生證明、住址證明、收入證明。"},{"order":3,"text":"第三步：填學生資助處「學生資助計劃」申請表。"},{"order":4,"text":"第四步：交俾學生資助處。"},{"order":5,"text":"第五步：等通知，批咗就會過數入你銀行戶口。"}]'::jsonb,
 'https://www.wfsfaa.gov.hk/tc/sfo/primarysecondary/tt/overview.php',
 'https://www.wfsfaa.gov.hk/tc/sfo/primarysecondary/tt/procedures.php',
 '在學資助處（學生資助處）',
 '2802 2345',
 '2026-06-01',
 '本系統只幫你整理資料及估計，不代表政府已批准申請。最終批核以政府部門公佈為準。請以官方連結最新資料為準。',
 '{"gradeLevels":["primary","secondary","tertiary"],"maxIncomeBand":"20k_30k","travelRelated":true,"boostSingleParent":true,"boostNewArrival":true}'::jsonb,
 true),

-- 3. 上網費津貼
('33333333-3333-3333-3333-333333333333',
 'internet-access-subsidy',
 '上網費津貼計劃',
 'Subsidy Scheme for Internet Access Charges',
 '上學開支',
 '幫有學生嘅低收入家庭，補貼部分屋企上網費，方便網上學習。',
 '屋企有學生、需要上網做功課或網上學習嘅低收入家庭。',
 '家庭收入較高、或者已無在學子女嘅家庭。',
 '["家庭有全日制就讀中小學或以下（或指定專上以下課程）嘅子女", "申請人為家長或監護人；學生為未婚香港居民並具香港居留身份", "每戶一年一次定額津貼", "家庭須通過入息審查（獲發全額或半額資格證明書）", "並非正領取綜援（綜援家庭嘅上網費由社署支付，不可同年重複領取）", "若已從其他公私營機構或學校獲上網費資助則不合資格"]'::jsonb,
 '["applicant_id","student_id","student_proof","address_proof","income_proof","bank_account"]'::jsonb,
 '[{"order":1,"text":"第一步：睇下屋企有冇學生要上網學習。"},{"order":2,"text":"第二步：準備身份證、學生證明、住址證明、收入或綜援證明。"},{"order":3,"text":"第三步：填上網費津貼申請表。"},{"order":4,"text":"第四步：交俾學生資助處或指定機構。"},{"order":5,"text":"第五步：等通知，批咗會發放定額津貼。"}]'::jsonb,
 'https://www.wfsfaa.gov.hk/tc/sfo/primarysecondary/tt/sia.php',
 'https://www.wfsfaa.gov.hk/tc/sfo/primarysecondary/tt/procedures.php',
 '在學資助處（學生資助處）',
 '2802 2345',
 '2026-06-01',
 '本系統只幫你整理資料及估計，不代表政府已批准申請。最終批核以政府部門公佈為準。請以官方連結最新資料為準。',
 '{"gradeLevels":["kindergarten","primary","secondary"],"maxIncomeBand":"20k_30k","internetRelated":true,"boostNewArrival":true}'::jsonb,
 true),

-- 4. 幼稚園及幼兒中心學費減免
('44444444-4444-4444-4444-444444444444',
 'kindergarten-fee-remission',
 '幼稚園及幼兒中心學費減免計劃',
 'Kindergarten and Child Care Centre Fee Remission Scheme',
 '上學開支',
 '幫有幼稚園或幼兒中心小朋友嘅低收入家庭，減免部分學費。',
 '有就讀幼稚園或幼兒中心子女、收入較低嘅家庭。',
 '子女已升上小學或以上、或者收入超出上限嘅家庭。',
 '["子女就讀參加「幼稚園教育計劃」嘅非牟利幼稚園，或社署註冊嘅幼兒中心（全日制）", "申請人為家長或監護人；子女為未婚香港居民並具香港居留身份", "2026/27 學年：幼稚園學童須於 2026 年 8 月 31 日滿 2 歲 8 個月（即 2023 年 12 月 31 日或之前出生）", "家庭須通過入息審查，可獲全免或半免學費", "持訪客簽證、雙程證、學生簽證或其受養人不合資格"]'::jsonb,
 '["applicant_id","student_id","student_proof","address_proof","income_proof","bank_account"]'::jsonb,
 '[{"order":1,"text":"第一步：睇下你個小朋友係咪讀緊幼稚園或幼兒中心。"},{"order":2,"text":"第二步：準備身份證、出世紙、住址證明、收入證明。"},{"order":3,"text":"第三步：填學費減免申請表。"},{"order":4,"text":"第四步：交俾學生資助處。"},{"order":5,"text":"第五步：等通知，批咗會直接減學費。"}]'::jsonb,
 'https://www.wfsfaa.gov.hk/tc/sfo/preprimary/kcfr/overview.php',
 'https://www.wfsfaa.gov.hk/tc/sfo/preprimary/kcfr/procedures.php',
 '在學資助處（學生資助處）',
 '2802 2345',
 '2026-06-01',
 '本系統只幫你整理資料及估計，不代表政府已批准申請。最終批核以政府部門公佈為準。請以官方連結最新資料為準。',
 '{"gradeLevels":["kindergarten"],"maxIncomeBand":"30k_40k","boostSingleParent":true,"boostNewArrival":true}'::jsonb,
 true),

-- 5. 綜援學生相關支援
('55555555-5555-5555-5555-555555555555',
 'cssa-student-support',
 '綜援學生相關支援',
 'Comprehensive Social Security Assistance (Student-related)',
 '綜合援助',
 '已領取綜援嘅家庭，子女讀書嘅學習津貼通常已經包喺綜援度，毋須另外申請書簿等津貼。',
 '正領取綜援、有在學子女嘅家庭。',
 '未領取綜援嘅家庭（應改為申請學生資助計劃）。',
 '["家庭正領取綜合社會保障援助（綜援）", "符合居港規定（一般須成為香港居民滿 1 年及居港滿 1 年；未滿 18 歲人士可獲豁免）", "通過入息及資產審查（以整個住戶為單位計算）", "有就讀由幼兒中心至中學嘅在學子女", "學校相關開支（書簿、車船、上網費、就學津貼等）由社署按綜援個案發放", "綜援家庭毋須（亦不可）就同一項目另向學生資助處申請"]'::jsonb,
 '["applicant_id","student_id","student_proof","cssa_proof","bank_account"]'::jsonb,
 '[{"order":1,"text":"第一步：確認你屋企正領緊綜援。"},{"order":2,"text":"第二步：準備綜援文件、學生證明、身份證。"},{"order":3,"text":"第三步：向你個案嘅社會保障部職員講有在學子女。"},{"order":4,"text":"第四步：交學生相關證明俾社會福利署。"},{"order":5,"text":"第五步：學習津貼會隨綜援一齊發放。"}]'::jsonb,
 'https://www.swd.gov.hk/tc/pubsvc/socsecu/comprehens/cssa/',
 'https://www.swd.gov.hk/tc/pubsvc/socsecu/comprehens/cssa/',
 '社會福利署',
 '2343 2255',
 '2026-06-01',
 '本系統只幫你整理資料及估計，不代表政府已批准申請。最終批核以政府部門公佈為準。請以官方連結最新資料為準。',
 '{"requiresCssa":true,"boostSen":true,"boostSingleParent":true}'::jsonb,
 true),

-- 6. 在職家庭津貼
('66666666-6666-6666-6666-666666666666',
 'working-family-allowance',
 '在職家庭津貼計劃',
 'Working Family Allowance Scheme',
 '綜合援助',
 '幫有人返工但收入唔高嘅家庭。除咗家庭津貼，仲有兒童津貼幫補在學子女開支。',
 '有家庭成員返工、收入唔高、又有在學子女嘅家庭。',
 '正領取綜援嘅家庭（綜援同在職家庭津貼唔可以同時領取）。',
 '["住戶並非領取綜援（綜援與職津不可同時領取）", "住戶有成員從事有薪工作並達到每月工時要求", "住戶每月收入及資產不超過指定上限（設不同津貼級別）", "設兒童津貼，補助合資格在學或年幼子女", "住戶成員一般須為香港居民並通常居於香港", "工時門檻、入息上限及金額每年公布，以官方最新資料為準"]'::jsonb,
 '["applicant_id","student_id","student_proof","address_proof","income_proof","bank_account","tenancy_agreement"]'::jsonb,
 '[{"order":1,"text":"第一步：睇下屋企有冇人返緊工，又有冇在學子女。"},{"order":2,"text":"第二步：準備身份證、入息證明、工時證明、住址證明。"},{"order":3,"text":"第三步：填在職家庭津貼申請表。"},{"order":4,"text":"第四步：交俾在職家庭津貼辦事處。"},{"order":5,"text":"第五步：等通知，批咗會按月或一筆過過數。"}]'::jsonb,
 'https://www.wfsfaa.gov.hk/wfao/tc/index.htm',
 'https://www.wfsfaa.gov.hk/wfao/tc/application/forms.htm',
 '在職家庭津貼辦事處',
 '2558 3000',
 '2026-06-01',
 '本系統只幫你整理資料及估計，不代表政府已批准申請。最終批核以政府部門公佈為準。請以官方連結最新資料為準。',
 '{"maxIncomeBand":"30k_40k","excludeIfCssa":true,"boostSingleParent":true,"boostNewArrival":true}'::jsonb,
 true)

on conflict (id) do nothing;

-- ---------- 設定現有 6 項津貼嘅受惠群組 ----------
update public.subsidy_schemes set audience = '["student","low_income"]'::jsonb where id = '11111111-1111-1111-1111-111111111111';
update public.subsidy_schemes set audience = '["student","low_income"]'::jsonb where id = '22222222-2222-2222-2222-222222222222';
update public.subsidy_schemes set audience = '["student","low_income"]'::jsonb where id = '33333333-3333-3333-3333-333333333333';
update public.subsidy_schemes set audience = '["student","low_income"]'::jsonb where id = '44444444-4444-4444-4444-444444444444';
update public.subsidy_schemes set audience = '["low_income","student"]'::jsonb where id = '55555555-5555-5555-5555-555555555555';
update public.subsidy_schemes set audience = '["low_income"]'::jsonb where id = '66666666-6666-6666-6666-666666666666';

-- ---------- 長者 / 殘疾群組（金額、年齡、資產上限每年由政府公布，需人手核實） ----------
insert into public.subsidy_schemes
  (id, slug, name_zh, name_en, category, audience, summary, suitable_for, not_suitable_for,
   eligibility, documents, steps, official_url, form_url, department, phone,
   last_verified, disclaimer, rule, active)
values
-- 7. 長者生活津貼
('77777777-7777-7777-7777-777777777777',
 'old-age-living-allowance', '長者生活津貼', 'Old Age Living Allowance (OALA)', '長者津貼',
 '["elderly","low_income"]'::jsonb,
 '俾 65 歲或以上、收入同資產唔多嘅長者嘅每月現金津貼。金額同資產上限每年由政府公布，請以官方為準。',
 '65 歲或以上、收入及資產較少嘅長者。',
 '資產或收入超出上限、或正領取綜援嘅長者（唔可以同時領取）。',
 '["年滿 65 歲", "成為香港居民滿 7 年，並在申請前連續居港滿 1 年（1 年內離港不超過 90 日視為居港）", "每月入息及資產不超過上限（2026 年 2 月 1 日起：單身 入息 $10,900／資產 $415,000；夫婦 $16,680／$630,000）", "並非同時領取高齡津貼（生果金）、傷殘津貼或綜援", "領款期間須繼續居於香港；被羈押或入住懲教院所期間不可領取", "已婚／同居者須一併申報配偶／同居伴侶嘅入息及資產，按「夫婦」上限計算"]'::jsonb,
 '["applicant_id","age_proof","address_proof","income_proof","asset_proof","bank_account"]'::jsonb,
 '[{"order":1,"text":"第一步：睇下你係咪夠 65 歲。"},{"order":2,"text":"第二步：準備身份證、住址證明、收入同銀行結單。"},{"order":3,"text":"第三步：填長者生活津貼申請表。"},{"order":4,"text":"第四步：交俾社會福利署。"},{"order":5,"text":"第五步：批咗會每月過錢入你戶口。"}]'::jsonb,
 'https://www.swd.gov.hk/tc/pubsvc/socsecu/ssallowance/ssaec/ssaec_oala/index.html',
 'https://www.swd.gov.hk/tc/pubsvc/socsecu/ssallowance/ssa_app/index.html',
 '社會福利署（社會保障）', '2343 2255', '2026-06-01',
 '本系統只幫你整理資料及估計，不代表政府已批准申請。最終批核以政府部門公佈為準。請以官方連結最新資料為準。',
 '{"requiresElderly":true,"minAgeBand":"65_69","maxAssetBand":"medium","maxIncomeBand":"10k_20k","excludeIfCssa":true,"meansTested":true,"boostLivingAlone":true}'::jsonb,
 true),
-- 8. 高齡津貼（生果金）
('88888888-8888-8888-8888-888888888888',
 'old-age-allowance', '高齡津貼（生果金）', 'Old Age Allowance (OAA)', '長者津貼',
 '["elderly"]'::jsonb,
 '俾 70 歲或以上長者嘅每月現金津貼，唔使入息審查。金額每年由政府公布。',
 '70 歲或以上嘅香港長者。',
 '未夠 70 歲，或已領取長者生活津貼 / 綜援嘅長者。',
 '["年滿 70 歲", "成為香港居民滿 7 年，並在申請前連續居港滿 1 年（1 年內離港不超過 90 日視為居港）", "毋須入息或資產審查（免審查）", "並非同時領取長者生活津貼、傷殘津貼或綜援", "領款期間須繼續居於香港；被羈押或入住懲教院所期間不可領取"]'::jsonb,
 '["applicant_id","age_proof","address_proof","bank_account"]'::jsonb,
 '[{"order":1,"text":"第一步：睇下你係咪夠 70 歲。"},{"order":2,"text":"第二步：準備身份證同銀行戶口資料。"},{"order":3,"text":"第三步：填高齡津貼申請表。"},{"order":4,"text":"第四步：交俾社會福利署。"},{"order":5,"text":"第五步：批咗會每月過錢入你戶口。"}]'::jsonb,
 'https://www.swd.gov.hk/tc/pubsvc/socsecu/ssallowance/ssaec/ssaec_oaa/index.html',
 'https://www.swd.gov.hk/tc/pubsvc/socsecu/ssallowance/ssa_app/index.html',
 '社會福利署（社會保障）', '2343 2255', '2026-06-01',
 '本系統只幫你整理資料及估計，不代表政府已批准申請。最終批核以政府部門公佈為準。請以官方連結最新資料為準。',
 '{"requiresElderly":true,"minAgeBand":"70_plus","excludeIfCssa":true,"meansTested":false}'::jsonb,
 true),
-- 9. 長者醫療券
('99999999-9999-9999-9999-999999999999',
 'elderly-health-care-voucher', '長者醫療券', 'Elderly Health Care Voucher Scheme', '醫療支援',
 '["elderly"]'::jsonb,
 '俾 65 歲或以上長者用嚟睇私家醫生、牙醫、中醫等基層醫療服務嘅醫療券。每年金額由政府公布。',
 '65 歲或以上、想睇私家基層醫療嘅長者。',
 '未夠 65 歲嘅人士。',
 '["年滿 65 歲", "持有效香港身份證，或入境事務處簽發嘅有效豁免登記證明書", "毋須入息或資產審查，亦無居港年期要求（非永久居民持有效證件亦合資格）", "領取綜援或傷殘津貼人士仍可使用醫療券", "憑年齡自動建立醫療券戶口，一般毋須另行申請", "曾以已失效逗留許可取得香港身份證者不合資格"]'::jsonb,
 '["applicant_id","age_proof"]'::jsonb,
 '[{"order":1,"text":"第一步：睇下你係咪夠 65 歲。"},{"order":2,"text":"第二步：帶身份證去睇已登記嘅醫生或牙醫。"},{"order":3,"text":"第三步：睇醫生時話用醫療券找數。"},{"order":4,"text":"第四步：系統會自動喺你戶口扣醫療券。"},{"order":5,"text":"第五步：唔使另外攞現金，直接抵扣診金。"}]'::jsonb,
 'https://www.hcv.gov.hk/tc/hcvs/background.html',
 'https://www.hcv.gov.hk/tc/hcvs/target_group.html',
 '衞生署（醫療券計劃）', '2838 2311', '2026-06-01',
 '本系統只幫你整理資料及估計，不代表政府已批准申請。最終批核以政府部門公佈為準。請以官方連結最新資料為準。',
 '{"requiresElderly":true,"minAgeBand":"65_69","medicalRelated":true,"meansTested":false}'::jsonb,
 true),
-- 10. 傷殘津貼
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
 'disability-allowance', '傷殘津貼', 'Disability Allowance', '殘疾支援',
 '["disability"]'::jsonb,
 '俾經評估為嚴重殘疾嘅香港居民嘅每月現金津貼，唔使入息審查。分普通同高額兩種。',
 '經醫生評估為嚴重殘疾嘅人士（任何年齡）。',
 '未經評估、或殘疾程度未達標準嘅人士。',
 '["經衞生署署長或醫院管理局行政總裁證明為「嚴重殘疾」（傷殘情況預計持續最少 6 個月）", "成為香港居民滿 7 年並在申請前連續居港滿 1 年（未滿 18 歲申請人可獲豁免居港年期規定）", "毋須入息或資產審查（免審查）", "並非同時領取其他社會保障津貼或綜援", "高額傷殘津貼：另須經證明日常生活需要他人經常照顧，且並非在受資助院舍／公立醫院等接受照顧", "領款期間須繼續居於香港；被羈押或入住懲教院所期間不可領取"]'::jsonb,
 '["applicant_id","address_proof","disability_proof","bank_account"]'::jsonb,
 '[{"order":1,"text":"第一步：搵醫生做殘疾評估。"},{"order":2,"text":"第二步：準備身份證、住址證明同醫生證明。"},{"order":3,"text":"第三步：填傷殘津貼申請表。"},{"order":4,"text":"第四步：交俾社會福利署。"},{"order":5,"text":"第五步：批咗會每月過錢入你戶口。"}]'::jsonb,
 'https://www.swd.gov.hk/tc/pubsvc/socsecu/ssallowance/ssaec/ssaec_nda/index.html',
 'https://www.swd.gov.hk/tc/pubsvc/socsecu/ssallowance/ssa_app/index.html',
 '社會福利署（社會保障）', '2343 2255', '2026-06-01',
 '本系統只幫你整理資料及估計，不代表政府已批准申請。最終批核以政府部門公佈為準。請以官方連結最新資料為準。',
 '{"requiresDisability":true,"meansTested":false,"boostLivingAlone":true}'::jsonb,
 true),
-- 11. 公共交通費用補貼 / $2 乘車優惠
('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
 'public-transport-subsidy', '公共交通費用補貼 / $2 乘車優惠',
 'Public Transport Fare Subsidy / $2 Concessionary Fares', '交通開支',
 '["elderly","disability","low_income"]'::jsonb,
 '$2 乘車優惠俾長者及合資格殘疾人士用優惠票價搭車船；公共交通費用補貼則幫返交通開支較高嘅市民。詳情及年齡以官方為準。',
 '長者、合資格殘疾人士，或每月交通開支較高嘅市民。',
 '不符合年齡 / 殘疾資格，而交通開支又唔高嘅人士。',
 '["$2 優惠：年滿 60 歲香港居民；或 60 歲以下、領綜援並評定為 100% 傷殘或領取傷殘津貼嘅殘疾人士", "$2 優惠：長者須用樂悠咭、殘疾人士須用載有「殘疾人士身分」嘅個人八達通（現金或匿名長者八達通不適用）", "$2 優惠不設入息審查，屬普及性優惠", "公共交通費用補貼：任何市民不論年齡及入息，每月公共交通開支超出門檻即可受惠，無須申請", "$2 優惠票價安排將於 2026 年 4 月 3 日起調整為「$2 劃一或 8 折」，以官方為準"]'::jsonb,
 '["applicant_id","age_proof"]'::jsonb,
 '[{"order":1,"text":"第一步：睇下你係咪長者或合資格殘疾人士。"},{"order":2,"text":"第二步：申請 / 使用個人八達通或樂悠咭。"},{"order":3,"text":"第三步：搭車船時嘟卡，自動用優惠票價。"},{"order":4,"text":"第四步：交通費補貼會按你嘅實際車費計算。"},{"order":5,"text":"第五步：補貼會經指定途徑發放（詳情睇官方）。"}]'::jsonb,
 'https://www.td.gov.hk/tc/gov_public_transport_fare_concession/index.html',
 'https://www.ptfss.gov.hk/tc-main.html',
 '勞工及福利局 / 運輸署', '187 2333', '2026-06-01',
 '本系統只幫你整理資料及估計，不代表政府已批准申請。最終批核以政府部門公佈為準。請以官方連結最新資料為準。',
 '{"travelRelated":true,"meansTested":false,"boostLivingAlone":true}'::jsonb,
 true)
on conflict (id) do nothing;

-- ---------- 長者社區 / 照顧 / 安全支援服務（服務名額及資助以官方為準，需人手核實） ----------
insert into public.subsidy_schemes
  (id, slug, name_zh, name_en, category, audience, summary, suitable_for, not_suitable_for,
   eligibility, documents, steps, official_url, form_url, department, phone,
   last_verified, disclaimer, rule, active)
values
-- 12. 離院長者綜合支援計劃
('cccccccc-cccc-cccc-cccc-cccccccccccc',
 'integrated-discharge-support-elderly', '離院長者綜合支援計劃（出院長者支援）',
 'Integrated Discharge Support Programme for Elderly Patients (IDSP)', '社區照顧',
 '["elderly","disability"]'::jsonb,
 '長者出院後，喺屋企提供一段時間嘅過渡支援，例如家居照顧、復康、送飯、護理，幫佢哋順利返返屋企生活。',
 '啱啱喺醫院出院、返屋企後需要短期照顧或復康支援嘅長者。',
 '毋須出院後照顧、或已入住院舍嘅長者。',
 '["為公立醫院嘅住院病人", "年滿 60 歲", "經醫院管理局「出院規劃小組」評估為出院後有較高非計劃再入院風險", "不設入息審查，按臨床及照顧需要評估", "由醫院、醫護或社工轉介，並無公開自行報名途徑"]'::jsonb,
 '["applicant_id","age_proof","address_proof","disability_proof"]'::jsonb,
 '[{"order":1,"text":"第一步：喺醫院出院前，同醫護或社工講你需要返屋企照顧。"},{"order":2,"text":"第二步：醫院會評估你嘅需要，再轉介去計劃。"},{"order":3,"text":"第三步：負責機構會聯絡你，安排上門支援。"},{"order":4,"text":"第四步：喺屋企接受一段時間嘅照顧、復康或送飯。"},{"order":5,"text":"第五步：情況穩定後，會轉介去長期社區服務。"}]'::jsonb,
 'https://www.swd.gov.hk/tc/pubsvc/elderly/cat_commcare/',
 'https://www.swd.gov.hk/tc/pubsvc/elderly/cat_commcare/',
 '社會福利署 / 醫院管理局', '2343 2255', '2026-06-01',
 '本系統只幫你整理資料及估計，不代表政府已批准申請。最終批核以政府部門公佈為準。請以官方連結最新資料為準。',
 '{"requiresElderly":true,"minAgeBand":"60_64","medicalRelated":true,"meansTested":false,"boostLivingAlone":true}'::jsonb,
 true),
-- 13. 平安鐘
('dddddddd-dddd-dddd-dddd-dddddddddddd',
 'personal-emergency-link', '平安鐘（個人緊急召援服務）', 'Personal Emergency Link Service', '安全支援',
 '["elderly","disability"]'::jsonb,
 '喺屋企裝一個緊急按鈕，長者一撳就有 24 小時服務中心幫手，遇到跌倒、唔舒服或危險可以即刻求助。有需要嘅長者可獲政府 / 關愛基金資助費用。',
 '獨居或日間獨自在家、想有多份安全保障嘅長者及殘疾人士。',
 '屋企長時間有人照顧、唔需要緊急召援嘅人士。',
 '["對象為獨居或缺乏照顧、有需要嘅長者及殘疾人士，提供 24 小時緊急支援", "綜援緊急召援系統津貼：領綜援並年滿 65 歲、獨居或家人未能照顧者；或 60–64 歲經證明超過 50% 殘疾／有特定醫療情況者", "資助計劃：由地區「關愛隊」識別及轉介嘅獨居／雙老長者及殘疾人士（限指定地區）", "部分經濟有困難人士可獲政府／關愛基金資助服務費用", "由認可服務機構（如長者安居協會）營運；詳細申請條件以官方及服務機構為準"]'::jsonb,
 '["applicant_id","age_proof","address_proof","income_proof"]'::jsonb,
 '[{"order":1,"text":"第一步：睇下你係咪獨居或日頭自己一個喺屋企。"},{"order":2,"text":"第二步：聯絡長者安居協會或你區嘅長者中心。"},{"order":3,"text":"第三步：如經濟有困難，同時申請費用資助。"},{"order":4,"text":"第四步：職員上門幫你安裝平安鐘。"},{"order":5,"text":"第五步：有事撳掣，24 小時服務中心即刻幫你。"}]'::jsonb,
 'https://www.swd.gov.hk/tc/pubsvc/elderly/cat_commcare/',
 'https://www.schsa.org.hk/tc/',
 '社會福利署（服務由長者安居協會等營運）', '2338 8312', '2026-06-01',
 '本系統只幫你整理資料及估計，不代表政府已批准申請。最終批核以政府部門公佈為準。請以官方連結最新資料為準。',
 '{"requiresElderly":true,"minAgeBand":"60_64","meansTested":false,"boostLivingAlone":true}'::jsonb,
 true),
-- 14. 長者社區照顧服務券
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee',
 'community-care-service-voucher', '長者社區照顧服務券',
 'Community Care Service Voucher for the Elderly (CCSV)', '社區照顧',
 '["elderly","disability","low_income"]'::jsonb,
 '俾身體機能有中度或以上缺損嘅長者一張服務券，可以揀日間中心或上門嘅照顧服務。費用按家庭收入分擔。',
 '身體機能較弱、需要日間或家居照顧，想自己揀服務嘅長者。',
 '身體健壯、暫時唔需要照顧服務嘅長者。',
 '["經「安老服務統一評估機制」評估並建議接受社區照顧或院舍照顧服務", "正在「中央輪候冊」輪候資助長期護理服務", "現時並未接受任何院舍照顧或任何資助社區照顧服務", "費用按家庭經濟狀況共同分擔", "官方以評估結果及輪候狀況界定資格，並無單獨列明最低年齡；以社署為準"]'::jsonb,
 '["applicant_id","age_proof","address_proof","income_proof","disability_proof"]'::jsonb,
 '[{"order":1,"text":"第一步：睇下長者身體機能係咪需要照顧。"},{"order":2,"text":"第二步：搵社工安排「安老服務統一評估」。"},{"order":3,"text":"第三步：評估合資格就會編配服務券。"},{"order":4,"text":"第四步：揀一間認可服務單位用服務券。"},{"order":5,"text":"第五步：按家庭收入付返一部分費用。"}]'::jsonb,
 'https://www.swd.gov.hk/tc/pubsvc/elderly/cat_commcare/psccsv/',
 'https://www.swd.gov.hk/tc/pubsvc/elderly/cat_commcare/psccsv/',
 '社會福利署', '2343 2255', '2026-06-01',
 '本系統只幫你整理資料及估計，不代表政府已批准申請。最終批核以政府部門公佈為準。請以官方連結最新資料為準。',
 '{"requiresElderly":true,"minAgeBand":"65_69","meansTested":true,"maxIncomeBand":"30k_40k","medicalRelated":true,"boostLivingAlone":true}'::jsonb,
 true),
-- 15. 家居照顧服務
('ffffffff-ffff-ffff-ffff-ffffffffffff',
 'home-care-services', '家居照顧服務（綜合家居 / 改善家居及社區照顧）',
 'Home Care & Community Care Services for the Elderly', '社區照顧',
 '["elderly","disability"]'::jsonb,
 '上門幫長者處理日常生活，例如送飯、洗澡、清潔、陪診、簡單護理同復康，等佢哋可以繼續喺屋企安心生活。',
 '行動不便或需要人照顧、想留喺屋企生活嘅長者。',
 '已入住院舍、或完全可自理嘅長者。',
 '["年滿 60 歲，居於社區並非入住院舍", "經「安老服務統一評估機制」或 interRAI 評估為體弱、輕度缺損或需要較高程度照顧，並獲建議接受相關服務", "提供上門送飯、起居照顧、護理、復康、陪診等服務", "殘疾人士或有社會需要嘅個人及家庭，須經社工轉介（家居支援服務）", "2026 年 4 月 1 日起綜合家居照顧與改善家居及社區照顧服務合併及易名；費用按家庭經濟狀況釐定"]'::jsonb,
 '["applicant_id","age_proof","address_proof"]'::jsonb,
 '[{"order":1,"text":"第一步：睇下長者日常生活需唔需要人幫手。"},{"order":2,"text":"第二步：聯絡你區嘅長者中心或社工。"},{"order":3,"text":"第三步：接受需要評估。"},{"order":4,"text":"第四步：安排上門服務，例如送飯、洗澡、陪診。"},{"order":5,"text":"第五步：按需要定期跟進同調整服務。"}]'::jsonb,
 'https://www.swd.gov.hk/tc/pubsvc/elderly/cat_commcare/homebase_ccs/index.html',
 'https://www.swd.gov.hk/tc/pubsvc/elderly/cat_commcare/homebase_ccs/index.html',
 '社會福利署', '2343 2255', '2026-06-01',
 '本系統只幫你整理資料及估計，不代表政府已批准申請。最終批核以政府部門公佈為準。請以官方連結最新資料為準。',
 '{"requiresElderly":true,"minAgeBand":"60_64","medicalRelated":true,"meansTested":false,"boostLivingAlone":true}'::jsonb,
 true),
-- 16. 廣東計劃 / 福建計劃
('a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1',
 'guangdong-fujian-scheme', '廣東計劃 / 福建計劃', 'Guangdong Scheme / Fujian Scheme', '長者津貼',
 '["elderly"]'::jsonb,
 '俾選擇移居廣東或福建嘅合資格香港長者，可以繼續每月領取高齡津貼（生果金），唔使返香港都收到。',
 '移居咗廣東或福建、又符合資格嘅香港長者。',
 '仍然長期居住香港嘅長者（應申請本地長者津貼）。',
 '["已移居或選擇居於廣東／福建", "長者生活津貼須年滿 65 歲；高齡津貼須年滿 70 歲", "成為香港居民滿 7 年並在申請前連續居港滿 1 年（1 年內離港不超過 90 日視為居港）", "領款期間須持續居於廣東／福建（設許可離開日數限制）", "並非同時領取其他社會保障津貼或綜援；如屬公屋租戶，離港前須交回單位", "長者生活津貼申請人另須入息及資產不超過上限（高齡津貼則免審查）"]'::jsonb,
 '["applicant_id","age_proof","bank_account"]'::jsonb,
 '[{"order":1,"text":"第一步：睇下你係咪已移居或打算移居廣東或福建。"},{"order":2,"text":"第二步：準備身份證同銀行戶口資料。"},{"order":3,"text":"第三步：填廣東計劃或福建計劃申請表。"},{"order":4,"text":"第四步：交俾社會福利署。"},{"order":5,"text":"第五步：批咗會每月過錢入你戶口，唔使返港。"}]'::jsonb,
 'https://www.swd.gov.hk/gds/index.html',
 'https://www.swd.gov.hk/gds/doc/2026/GDS_and_FJS_Application_Form_internet__version_2026.pdf',
 '社會福利署（社會保障）', '2343 2255', '2026-06-01',
 '本系統只幫你整理資料及估計，不代表政府已批准申請。最終批核以政府部門公佈為準。請以官方連結最新資料為準。',
 '{"requiresElderly":true,"minAgeBand":"65_69","meansTested":false}'::jsonb,
 true),
-- 17. 長者牙科服務資助
('b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2',
 'elderly-dental-assistance', '長者牙科服務資助計劃', 'Elderly Dental Assistance Programme', '醫療支援',
 '["elderly","low_income"]'::jsonb,
 '幫合資格長者免費或資助鑲牙同相關牙科治療，等佢哋食嘢同健康好啲。',
 '有需要脫牙、鑲牙，又正接受指定長者服務嘅長者。',
 '毋須牙科治療、或未符合指定服務條件嘅人士。',
 '["低收入長者，並符合其中一項：正領取長者生活津貼（即 65 歲或以上）；或屬社署資助家居照顧服務（IHCS／EHCCS）中收費第一或第二級別嘅使用者", "並非正領取綜援，亦未曾受惠於「長者牙科外展服務」", "每名合資格長者最多可接受服務兩次；第二次須年滿 75 歲且過去 5 年內未曾受惠", "由指定服務單位安排申請", "計劃由關愛基金資助；名額及詳情以官方為準"]'::jsonb,
 '["applicant_id","age_proof"]'::jsonb,
 '[{"order":1,"text":"第一步：睇下你係咪正用緊指定長者服務。"},{"order":2,"text":"第二步：向服務單位或社工查詢牙科資助。"},{"order":3,"text":"第三步：填申請表，安排牙科檢查。"},{"order":4,"text":"第四步：由認可牙醫提供鑲牙等治療。"},{"order":5,"text":"第五步：資助會直接減免治療費用。"}]'::jsonb,
 'https://www.communitycarefund.hk/',
 'https://www.communitycarefund.hk/',
 '社會福利署（關愛基金資助）', '2343 2255', '2026-06-01',
 '本系統只幫你整理資料及估計，不代表政府已批准申請。最終批核以政府部門公佈為準。請以官方連結最新資料為準。',
 '{"requiresElderly":true,"minAgeBand":"65_69","medicalRelated":true,"meansTested":false}'::jsonb,
 true)
on conflict (id) do nothing;

-- ---------- 同步寫入 normalized 文件表（可選用） ----------
insert into public.subsidy_documents (scheme_id, document_key, required)
select s.id, doc.value::text, true
from public.subsidy_schemes s,
     lateral jsonb_array_elements_text(s.documents) as doc(value)
on conflict do nothing;

-- ---------- 設定管理員（請改成你自己嘅 auth user id） ----------
-- 1) 先用 App 嘅電郵登入流程登入一次，喺 Supabase Auth → Users 搵到你嘅 UUID
-- 2) 解除下面註解並填入你嘅 UUID + email，再執行：
-- insert into public.admin_users (user_id, email)
-- values ('00000000-0000-0000-0000-000000000000', 'you@example.com')
-- on conflict (user_id) do nothing;
